FROM golang:1.23.6 AS builder

WORKDIR /multiversx

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go mod tidy

WORKDIR /multiversx/cmd/notifier

RUN go build -o notifier

# ===== SECOND STAGE ======
FROM ubuntu:24.10
RUN apt-get update && apt-get install -y openssl ca-certificates
COPY --from=builder /multiversx/cmd/notifier /multiversx

EXPOSE 8080 22111 80 443 5000

WORKDIR /multiversx

CMD ["./notifier", "--general-config", "config/config.devnet.toml", "--publisher-type", "servicebus"]