name: Trigger auto deployment for xoxno-notifier-devnet

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ add-azure-service-bus ]
    paths:
    - 'Dockerfile.devnet/**'
    - '.github/workflows/xoxno-notifier-devnet-AutoDeployTrigger-4e126791-d1a6-49b4-a66b-205363dff82f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.XOXNONOTIFIERDEVNET_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.XOXNONOTIFIERDEVNET_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.XOXNONOTIFIERDEVNET_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: xoxno.azurecr.io
          registryUsername: ${{ secrets.XOXNONOTIFIERDEVNET_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.XOXNONOTIFIERDEVNET_REGISTRY_PASSWORD }}
          containerAppName: xoxno-notifier-devnet
          resourceGroup: XOXNODev
          imageToBuild: xoxno.azurecr.io/xoxno-notifier-devnet:${{ github.sha }}
          dockerfilePath: Dockerfile.devnet


